

#### Schematic Specifications

##### Proficiency

- [ ] All pin names labeled
- [ ] All pin numbers labeled
- [ ] Crossing wires clearly identified as junction or unconnected
- [ ] Neat layout (e.g., clear organization and spacing)
- [ ] All parts labeled with part number
- [ ] All component values present

##### Excellence

- [ ] Standard symbols used for all components where applicable
- [ ] Signals "flow" from left to right where possible (e.g., inputs on left hand side, outputs on right hand side)
- [ ] Title block with author name, title, and date


#### Block Diagram (Required for labs 1, 2, 3 and 7)

##### Proficiency and Excellence

- [ ] Top-level block diagram present with one block per SystemVerilog module
- [ ] Blocks that contain other modules have their own block diagrams, or the hierarchy is depicted in the top level drawing.
- [ ] Each block is labeled with the module name. (Usually inside the block, upper left corner.)
- [ ] Each block is labeled with the instance name. (Usually outside the block, upper right corner.)
- [ ] Each block is labeled with every input and output port. (i.e.: the names of signals inside the module are written on the inner boundary.)
- [ ] The top level block has every net labeled. (i.e.: the names of signals outside of the submodules are all labeled.)
- [ ] Logic that is not wrapped in a module is drawn as gates.
- [ ] Pin numbers are attached to the outer perimeter of the top level block, capturing the mapping of logic signals to pins.
- [ ] Clock and reset nets are connected symbolically.

#### HDL & Code Specifications

##### Proficiency

- [ ] Descriptive filename that matches module name (e.g., `lab2_jb.sv`)
- [ ] One module per file
- [ ] Descriptive variable names
- [ ] Neat formatting (e.g., standard indentation, consistent formatting for variable names (kebab-case/snake_case/camelCase/PascalCase ))
- [ ] Descriptive and clear function/module names
- [ ] Comments to indicate the purpose of each function/module


##### Excellence

- [ ] Name, email, and date at the top of every file
- [ ] Comment at the top of each source code file to describe what is in it
- [ ] Clear and organized hierarchy (e.g., delineation between top level modules and submodules)
- [ ] Testbenches written for each individual module to demonstrate proper operation
- [ ] Testbench output for each module included in the report


#### Writeup/Summary

##### Proficiency and Excellence

- [ ] Statement of whether the design meets all the requirements. If not, list the shortcomings.
- [ ] Number of hours spent working on the lab are included.
- [ ] Writeup contains minimal spelling or grammar issues and any errors do not significantly detract from clarity of the writeup.
- [ ] AI prototype attempted and some reflection is recorded.
- [ ] (Optional) List comments or suggestions on what was particularly good about the assignment or what you think needs to change in future versions.

### Comments

Add specific notes here about the assignment.

<textarea style="width: 100%" id="comments" name="comments" rows="10" cols="10">

</textarea>