#### Proficiency

- [ ] Design makes use of at least one timer peripheral, accessed with writes to appropriate memory-mapped SFRs.
- [ ] Design uses an audio amplifier to drive the speaker.
- [ ] Design plays *Für Elise* from provided starter code
- [ ] Note durations match the durations specified in the starter code for *Für Elise* (i.e., the tune plays at the correct tempo)
- [ ] All rests (pauses with no sound) are played properly
- [ ] Calculations show that the system can create 220 Hz and 1000 Hz pitches within 1% accuracy. 
- [ ] Code uses `#define` macros for memory-mapped registers, copying the struct and base address design format from class.

#### Excellence

- [ ] Report contains accurate calculations for **minimum duration** supported
- [ ] Report contains accurate calculations for **maximum duration** supported
- [ ] Report contains accurate calculations for **minimum frequency** supported
- [ ] Report contains accurate calculations for **maximum frequency** supported
- [ ] Calculations show that **all notes in Für Elise** can be replicated to within 1% accuracy.  Comment on whether or not checking at 220 Hz and 1000 Hz is sufficient to prove that all notes are within error bounds.
- [ ] Code does not divide by zero or commit other mathematical errors.
- [ ] Design contains potentiometer to control the output volume.
- [ ] Design plays an extra composition of your choice. You need not compose the tune from scratch, it is acceptable to transpose an existing tune.