### Schematic Specifications

#### Proficiency

- [ ] Schematic correctly represents the circuit that was built on the breadboard.
- [ ] No parts of motherboard schematic replicated. Shows only off-board components. Indicate on-board components with a brief paragraph that links the motherboard schematic ([here](../../assets/doc/E155%20FA22%20Development%20Board%20Schematic.pdf)).
- [ ] No parts internal to the chip (e.g. internal pullup resistors) drawn on schematic. Indicate important pullups, capacitors, etc. with comments instead.
- [ ] All pin names labeled.
- [ ] All pin numbers labeled.
- [ ] Crossing wires clearly identified as junction or unconnected.
- [ ] Neat layout (e.g., clear organization and spacing).
- [ ] All parts labeled with part number.
- [ ] All component values present.

#### Excellence

- [ ] Standard symbols used for all components where applicable.
- [ ] Signals "flow" from left to right where possible (e.g., inputs on left hand side, outputs on right hand side, power on top, ground on bottom)
- [ ] Title block with author name, title, and date.
