---
title: Project Proposal Specs
format:
  html: default
  pdf: default
---

The goal of the proposal is to describe what you plan to build and how you plan to build it.
The specifications below provide the expectations for the project proposal.

It should be no longer than 2-pages worth of text along with any technical documentation needed (i.e., diagrams, tables, or other figures do not count against the 2-page limit).
The point is for you to make your description clear, direct, and concise.

While you are free to organize your proposal in the way that best suits your project, you should be sure to address the following sections:

- Project Description and Overview
- FPGA Design Details
- MCU Design Details
- Calculations relevant to the system's performance - bandwidths, data rates, FFT widths, frame rates, etc.
- Diagram indicating chips, connection, and protocols
- Schedule and work breakdown (e.g., Gantt chart or similar)
- Bill of Materials/Budget

{{< pagebreak >}}

## General

### Proficiency

- [ ] Bill of materials included with list of all items needed for the project
- [ ] Project lists specifications for design
- [ ] Identifies the riskiest element of the project

### Excellence

- [ ] Completely clear what the project must do to meet specs.
- [ ] Rough timeline included which lists the tasks which need to be completed, the order in which they will be pursued, and the time they are expected to take.
- [ ] Short explanation of how the project tasks will be divided among the team members.
- [ ] Calculation of performance critical parameters is present.
- [ ] Writing is well organized
- [ ] No grammar or spelling issues.

## Technical 

### Proficiency

- [ ] Describes microcontroller use
- [ ] Project uses FPGA
- [ ] Project uses new hardware

### Excellence

- [ ] Project uses functionality of microcontroller not previously covered in labs
- [ ] Project uses functionality of FPGA not previously covered in labs
- [ ] Project uses new non-trivial new hardware (e.g., digital chip with non-trivial interface)


## Documentation

### Proficiency

- [ ] Block diagram of system provided showing all elements of the design and their connections.

### Excellence

- [ ] Bill of materials includes part numbers, quantities, and prices for all components. Prices for components available in the stock room should be indicated as "stockroom".
- [ ] Block diagram of system clearly describes all protocols and interfaces.
- [ ] Block diagram is computer drawn and neatly laid out.