---
title: "Lab"
---

## Lab Admin

A Google Sheet for scheduling lab checkoffs can be found [here]({{< var lab-checkoff-gsheet-url >}}). (g.hmc credentials required)

Any code for the labs may be found on the [E155 course Github repository]({{< var github-url >}}).

## List of E155 Labs

* [Lab 1 - Board Assembly and Testing](/lab/lab1)
* [Lab 2 - Multiplexed 7-Segment Display](/lab/lab2)
* [Lab 3 - Keypad Scanner](/lab/lab3)
* [Lab 4 - Digital Audio](/lab/lab4)
* [Lab 5 - Interrupts](/lab/lab5)
* [Lab 6 - The Internet of Things and Serial Peripheral Interface](/lab/lab6)
  * [DS1722 Datasheet](https://datasheets.maximintegrated.com/en/ds/DS1722.pdf)
  * [Serial Protocol Decoding on the RIGOL MSO1104z](/assets/lab/Serial Protocol Decoding on the RIGOL MSO1104z.pdf)
* [Lab 7 - The Advanced Encryption Standard (AES)](/lab/lab7)

## Lab Report Template

You can find a template [here](./lab-report-template/lab-report-template.qmd) which provides a template for the content and format for the short reports which should accompany each of your labs.